### PR TITLE
Hide commit button tooltip after committing

### LINKED ISSUE #1387: "Ctrl-enter to commit" tooltip is not disposed
### Prerequisites

* Have you tried to reproduce the problem in [Safe Mode][safe-mode]?
* Have you followed all applicable steps in the [debugging guide][debugging-guide]?
* Have you checked the FAQs on the [message board][message-board] for common solutions?
* Have you checked that your issue [isn't already filed][already-filed]?

[safe-mode]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/github/issues

### Description

Here's a gif!  The "ctrl-enter to commit" tooltip is not disposed properly after a commit happens and sticks around until the "Commit" button becomes active again.
orphaned-tooltip

### Steps to Reproduce

1. Have something to commit
2. Hover over the Commit button until the tooltip shows up
3. Commit

**Expected behavior:** Tooltip to disappear

**Actual behavior:** Tooltip stays around

**Reproduces how often:** 100%

### Versions

```
Atom    : 1.27.0-dev-067add71f
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
```

### PR DESCRIPTION
**Pull request by kuychaco**
Fixes #1387

### CODE REVIEW

File: lib/views/commit-view.js [hunk 1]
```diff
@@ -83,7 +75,16 @@ export default class CommitView extends React.Component {
...
+      if (!FakeKeyDownEvent) {
+        FakeKeyDownEvent = class extends CustomEvent {
+          constructor(kCode) {
+            super('keydown');
+            this.keyCode = kCode;
+          }
+        };
+      }
+
+      const fakeEvent = new FakeKeyDownEvent(keyCode);
```
Comment (kuychaco) [inline lib/views/commit-view.js]: /cc @annthurium - took the liberty to 🎨 this. Hope that's okay!

Comment (annthurium) [reply lib/views/commit-view.js]: awesome, thank you!!
