### PR TITLE
Fix: wrong prefix on PR files changed

### LINKED ISSUE #1853: Changed files tabs show inaccurate file paths
### Description

It is a `git diff` default behaviour to use `a/` to prefix source file and `b/` to prefix destination file (see the [docs](https://git-scm.com/docs/git-diff#_generating_patches_with_p) for more detail). Within the codebase of the pacakge, we work around this by using [`--no-prefix` flag](https://github.com/atom/github/blob/master/lib/git-shell-out-strategy.js#L612) to get diffs, but changed files tab instead get the diff from GitHub API, which doesn't have a no-prefix option. As a result, some file paths in PR changed files have their prefixes included as well. 

### Steps to Reproduce

1. Open "Files" tab in PR view
2. Observe that some file paths have `b/` in front of it.

**Expected behavior:**

File patch title shows the accurate file path.

**Actual behavior:**

Some file paths show up with `b/` in front of it.

**Reproduces how often:**

100%

### Additional Information
image

### PR DESCRIPTION
**Pull request by vanessayuenn**
fixes #1853

### CODE REVIEW

File: lib/containers/pr-changed-files-container.js [hunk 1]
```diff
@@ -59,7 +59,16 @@ export default class PullRequestChangedFilesContainer extends React.Component {
   }
 
   buildPatch(rawDiff) {
-    const diffs = parseDiff(rawDiff);
+    const diffs = parseDiff(rawDiff).map(diff => {
```
Comment (annthurium) [inline lib/containers/pr-changed-files-container.js]: do we also need to worry about where we're using `parseDiff` in `git-shell-out-strategy`?  If so, we should consider extracting this functionality to some kind of helper.

I seem to remember some chatter that git gives us different output than the REST api does, so this might not actually be a problem.

**Review by annthurium — APPROVED** [review]
Thanks @vanessayuenn for fixing!

Left one question, but it's non blocking.

File: lib/containers/pr-changed-files-container.js (hunk 1 above)
Comment (vanessayuenn) [reply lib/containers/pr-changed-files-container.js]: yes

Comment (vanessayuenn) [reply lib/containers/pr-changed-files-container.js]: >I seem to remember some chatter that git gives us different output than the REST api does,

Indeed! It is a git diff default behaviour to use `a/` to prefix the source file and `b/` to prefix the destination file. In `git-shell-out-strategy`, we work around this by using `--no-prefix` flag to get diffs, but for changed files tab, we don't have that option since we're getting the diff from the REST API.
