### PR TITLE
Fix regexp for GSOS#getRemotes

### LINKED ISSUE #858: Having a pushurl config in git make the package crash
[Theses lines](https://github.com/atom/github/blob/master/lib/git-shell-out-strategy.js#L634-L637) try to parse remotes and fails if there is a [pushurl config](https://git-scm.com/docs/git-push#_remotes_a_id_remotes_a).
The package fails with a `git-shell-out-strategy.js:871 Uncaught (in promise) TypeError: Cannot read property '1' of null(…)`

After a bit of investigation it seems like the [regex here](https://github.com/atom/github/blob/master/lib/git-shell-out-strategy.js#L629) is not correctly escaped and therefore match pushurl too.

```
$ git config --local --get-regexp '^remote..*.url$'
remote.origin.url git@github.com:paradoxxxzero/whatever.git
remote.origin.pushurl git@github.com:paradoxxxzero/whatever.git
```

```
$ git config --local --get-regexp '^remote\..*\.url$'
remote.origin.url git@github.com:paradoxxxzero/whatever.git
```

### PR DESCRIPTION
**Pull request by kuychaco**
Fixes #858

### CODE REVIEW

File: lib/git-shell-out-strategy.js [hunk 1]
```diff
@@ -626,7 +626,8 @@ export default class GitShellOutStrategy {
   }
 
   async getRemotes() {
-    let output = await this.getConfig(['--get-regexp', '^remote..*.url$'], {local: true});
+    // eslint-disable-next-line no-useless-escape
+    let output = await this.getConfig(['--get-regexp', '^remote\..*\.url$'], {local: true});
```
Comment (smashwilson) [inline lib/git-shell-out-strategy.js]: I think you need to double-escape the `\` (hence the linter complaining about it):

```
> console.log('foo\.bar')
foo.bar
undefined
> console.log('foo\\.bar')
foo\.bar
undefined
```

Comment (kuychaco) [inline lib/git-shell-out-strategy.js]: oh good call. heh infinite escaping
