### PR TITLE
Handle ghost users (deleted accounts)

### LINKED ISSUE #1921: Stack trace on opening GitHub tab
### Prerequisites

* Have you tried to reproduce the problem in [Safe Mode][safe-mode]?
* Have you followed all applicable steps in the [debugging guide][debugging-guide]?
* Have you checked the FAQs on the [message board][message-board] for common solutions?
* Have you checked that your issue [isn't already filed][already-filed]?

[safe-mode]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/github/issues

### Description

When attempting to open the GitHub tab on [atom/find-and-replace](https://github.com/atom/find-and-replace), I'm seeing a stacktrace in the dev console.

### Steps to Reproduce

1. Clone atom/find-and-replace and open it in Atom.
2. Click the GitHub status bar tile to open the GitHub tab.

**Expected behavior:**

The GitHub tab should open and a list of open pull requests should appear.

**Actual behavior:**

The following stacktrace appears in the dev console:

```
/Users/smashwilson/.atom/packages/github/node_modules/react-dom/cjs/react-dom.production.min.js:179 TypeError: Cannot read property 'login' of null
    at new Issueish (issueish.js? [sm]:2)
    at issueishes.props.results.map.node (issueish-list-controller.js? [sm]:15)
    at Array.map (<anonymous>)
    at getDerivedStateFromProps (issueish-list-controller.js? [sm]:15)
    at Qf (/Users/smashwilson/.atom/packages/github/node_modules/react-dom/cjs/react-dom.production.min.js:133)
    at $f (/Users/smashwilson/.atom/packages/github/node_modules/react-dom/cjs/react-dom.production.min.js:138)
    at wg (/Users/smashwilson/.atom/packages/github/node_modules/react-dom/cjs/react-dom.production.min.js:157)
    at Ag (/Users/smashwilson/.atom/packages/github/node_modules/react-dom/cjs/react-dom.production.min.js:169)
    at lh (/Users/smashwilson/.atom/packages/github/node_modules/react-dom/cjs/react-dom.production.min.js:204)
    at mh (/Users/smashwilson/.atom/packages/github/node_modules/react-dom/cjs/react-dom.production.min.js:205)
    at Ph (/Users/smashwilson/.atom/packages/github/node_modules/react-dom/cjs/react-dom.production.min.js:220)
    at Qh (/Users/smashwilson/.atom/packages/github/node_modules/react-dom/cjs/react-dom.production.min.js:219)
    at sh (/Users/smashwilson/.atom/packages/github/node_modules/react-dom/cjs/react-dom.production.min.js:216)
    at Uf (/Users/smashwilson/.atom/packages/github/node_modules/react-dom/cjs/react-dom.production.min.js:214)
    at Object.enqueueSetState (/Users/smashwilson/.atom/packages/github/node_modules/react-dom/cjs/react-dom.production.min.js:134)
    at ReactRelayQueryRenderer.G.setState (/Users/smashwilson/.atom/packages/github/node_modules/react/cjs/react.production.min.js:13)
    at retryCallbacks.handleDataChange (/Users/smashwilson/.atom/packages/github/node_modules/react-relay/lib/ReactRelayQueryRenderer.js:149)
    at /Users/smashwilson/.atom/packages/github/node_modules/react-relay/lib/ReactRelayQueryFetcher.js:291
    at Array.forEach (<anonymous>)
    at ReactRelayQueryFetcher._onQueryDataAvailable (/Users/smashwilson/.atom/packages/github/node_modules/react-relay/lib/ReactRelayQueryFetcher.js:290)
    at Object.next (/Users/smashwilson/.atom/packages/github/node_modules/react-relay/lib/ReactRelayQueryFetcher.js:157)
    at Object.next (/Users/smashwilson/.atom/packages/github/node_modules/relay-runtime/lib/RelayObservable.js:560)
    at Object.next (/Users/smashwilson/.atom/packages/github/node_modules/relay-runtime/lib/RelayObservable.js:560)
    at Object.next (/Users/smashwilson/.atom/packages/github/node_modules/relay-runtime/lib/RelayObservable.js:226)
    at Object.next (/Users/smashwilson/.atom/packages/github/node_modules/relay-runtime/lib/RelayObservable.js:560)
    at Object.next (/Users/smashwilson/.atom/packages/github/node_modules/relay-runtime/lib/RelayObservable.js:560)
    at /Users/smashwilson/.atom/packages/github/node_modules/relay-runtime/lib/RelayObservable.js:491
    at _subscribe (/Users/smashwilson/.atom/packages/github/node_modules/relay-runtime/lib/RelayObservable.js:608)
    at RelayObservable.subscribe (/Users/smashwilson/.atom/packages/github/node_modules/relay-runtime/lib/RelayObservable.js:314)
    at Object.next (/Users/smashwilson/.atom/packages/github/node_modules/relay-runtime/lib/RelayObservable.js:375)
```

**Reproduces how often:**

100%

### Versions

```
github@0.24.0 (atom/github#b5091255)
```

### Additional Information

I'm guessing that we're assuming `login` is a required property in the GraphQL schema when it is not. I suspect the problem is this PR opened by a now-deleted user account:

screen shot 2019-01-25 at 9 57 43 am

### LINKED ISSUE #2014: Non-existent (Ghost) users Pull Requests crash Github tab
*Edit by @rsese to add alternate repro steps with a public repository where I found a now :ghost:-authored PR: https://github.com/atom/command-palette/pull/76*

1. Clone https://github.com/atom/command-palette
2. Toggle the GitHub tab `GitHub: Toggle GitHub Tab` (at this point https://github.com/atom/command-palette/pull/76 is filtered out and not shown in the `Open pull requests` list)
3. `GitHub: Open Issue or Pull Request` and enter `https://github.com/atom/command-palette/pull/76`

The Git and GitHub tabs go blank and I see this error in console:

```
TypeError: Cannot read property 'url' of null
    at BarePullRequestDetailView.render (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:14:4094739)
    at Qg (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:14:2426345)
    at Og (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:14:2426140)
    at Tg (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:14:2429973)
    at bi (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:14:2453979)
    at ci (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:14:2454363)
    at Di (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:14:2461253)
    at Yh (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:14:2460633)
    at Xh (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:14:2459654)
    at qf (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:14:2458525)
    at Object.enqueueSetState (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:14:2408169)
    at ReactRelayQueryRenderer.E.setState (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:14:2336882)
    at n.handleDataChange (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:14:4329082)
    at /Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:14:4514840
    at Array.forEach (<anonymous>)
    at ReactRelayQueryFetcher._onQueryDataAvailable (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:14:4514813)
    at Object.next (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:14:4512609)
    at Object.next (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:14:4549167)
    at Object.next (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:14:4549167)
    at Object.next (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:14:4547953)
    at Object.next (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:14:4549167)
    at Executor._next (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:14:4727251)
    at Object.next (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:14:4725336)
    at Object.next (/Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:14:4549167)
    at /Applications/Atom Beta.app/Contents/Resources/app/static/<embedded>:14:4551491
    at <anonymous>
```

At this point, you need to reload the window to use the Git and GitHub tabs again.

1.36.0-beta-2 on macOS 10.12.6.

---

### Prerequisites

* Have you tried to reproduce the problem in [Safe Mode][safe-mode]?
* Have you followed all applicable steps in the [debugging guide][debugging-guide]?
* Have you checked the FAQs on the [message board][message-board] for common solutions?
* Have you checked that your issue [isn't already filed][already-filed]?

[safe-mode]: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
[debugging-guide]: http://flight-manual.atom.io/hacking-atom/sections/debugging/
[message-board]: https://discuss.atom.io/c/faq
[already-filed]: https://github.com/atom/github/issues

### Description

When a user deletes their account, any open pull requests they created will crash the github tab

### Steps to Reproduce

1. Create and add a user to a private repository
2. Have the user open a pull request
3. Delete the user account
4. Open github tab 

**Expected behavior:**

Expected the tab to show the pull requests and associate them with 'ghost' the generic Github user that is displayed on the PR within Github's UI.

**Actual behavior:**

Tab crashes and takes git tab with it

**Reproduces how often:**

Anytime you open the tab and the pull request remains open

### Versions

All

### Additional Information

We noticed this in a private repository, but I assume the issue will exist for public repositories as well

### PR DESCRIPTION
**Pull request by kuychaco**
**Please be sure to read the [contributor's guide to the GitHub package](https://github.com/atom/github/blob/master/CONTRIBUTING.md) before submitting any pull requests.**

### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* Suggestion: You can use checklists to keep track of progress for the sections on metrics, tests, documentation, and user research.

### Description of the Change

This PR introduces changes to handle ghost users throughout our UI. When a user account has been deleted, activity by them is replaced to be a "Deleted user" account -- https://github.com/ghost

Prior to this change, users were seeing errors thrown when looking up properties on a `null` user.

To address this, I created a GHOST_USER object in our `lib/helpers.js` file and used it throughout the codebase when we'd get back `null` from the GitHub graphql API.

```
export const GHOST_USER = {
  login: 'ghost',
  avatarUrl: 'https://avatars1.githubusercontent.com/u/10137?v=4',
  url: 'https://github.com/ghost',
};
```

### Screenshot/Gif

N/A

### Alternate Designs

N/A

### Benefits

No more errors!

### Possible Drawbacks

None.

### Applicable Issues

Fixes #2014 
Fixes #1921

### Metrics

N/A

### Tests

TODO

### Documentation

N/A

### Release Notes

> Handle ghost users (deleted accounts) throughout the GitHub integration UI

### User Experience Research (Optional)

N/A

### CODE REVIEW

File: lib/containers/accumulators/review-comments-accumulator.js [hunk 1]
```diff
@@ -67,6 +67,7 @@ export default createPaginationContainer(BareReviewCommentsAccumulator, {
             author {
               avatarUrl
               login
+              url
```
Comment (smashwilson) [inline lib/containers/accumulators/review-comments-accumulator.js]: Oh interesting, we were just URL-hacking this in before? Yeah, much cleaner to get it from GraphQL 👍

File: test/builder/graphql/issue.js [hunk 2]
```diff
@@ -18,7 +18,7 @@ export const IssueBuilder = createSpecBuilderClass('Issue', {
   number: {default: 123},
   state: {default: 'OPEN'},
   bodyHTML: {default: '<h1>HI</h1>'},
-  author: {linked: UserBuilder},
+  author: {linked: UserBuilder, default: null},
```
Comment (smashwilson) [inline test/builder/graphql/issue.js]: I really like defaulting these to `null` in the builder. This way we'll catch _anywhere_ that an author is fetched from GraphQL but we don't account for it being nullable 👍

File: test/builder/graphql/timeline.js [hunk 3]
```diff
@@ -32,7 +32,7 @@ export const CommitBuilder = createSpecBuilderClass('Commit', {
 
 export const CommitCommentBuilder = createSpecBuilderClass('CommitComment', {
   id: {default: nextID},
-  author: {linked: UserBuilder},
+  author: {linked: UserBuilder, default: null},
```
Comment (smashwilson) [inline test/builder/graphql/timeline.js]: You _could_ add `nullable: true` here too. All that really does is let you use the `.nullAuthor()` function on the generated builder, though, which is functionally equivalent to `.author(null)`.

File: test/builder/graphql/timeline.js [hunk 4]
```diff
@@ -61,7 +61,7 @@ export const HeadRefForcePushedEventBuilder = createSpecBuilderClass('HeadRefFor
 }, 'Node');
 
 export const IssueCommentBuilder = createSpecBuilderClass('IssueComment', {
-  author: {linked: UserBuilder},
+  author: {linked: UserBuilder, default: null},
```
Comment (smashwilson) [inline test/builder/graphql/timeline.js]: Same here ☝️

File: test/fixtures/factories/commit-comment-thread-results.js [hunk 5]
```diff
@@ -6,6 +6,7 @@ export function createCommitComment(opts = {}) {
   const o = {
     id: idGen.generate('comment-comment'),
     commitOid: '1234abcd',
+    includeAuthor: true,
```
Comment (smashwilson) [inline test/fixtures/factories/commit-comment-thread-results.js]: I've been trying to phase out these `test/fixtures/factories` methods in favor of GraphQL builders - the GraphQL builders are easier to write against (the builder structure maps directly to the query!) and they keep up with changes to our queries and the schema. It's tedious as hell, though, so I don't blame you for patching this in 😛
